// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6i2NNm5jQ7HfIDC6ro5byV3RDEme__wA',
    appId: '1:384073856983:web:9b2b7979c506c98ae5bd92',
    messagingSenderId: '384073856983',
    projectId: 'algonaid-4025a',
    authDomain: 'algonaid-4025a.firebaseapp.com',
    storageBucket: 'algonaid-4025a.firebasestorage.app',
    measurementId: 'G-91P0NC21L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNzkbNBcaYzOojXL17fSnlkQAXiZQp-A',
    appId: '1:384073856983:android:35f69fa2b045c6c1e5bd92',
    messagingSenderId: '384073856983',
    projectId: 'algonaid-4025a',
    storageBucket: 'algonaid-4025a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQesXJs6UoJV0vnKuPwrrCXqjsiIa6xw',
    appId: '1:384073856983:ios:3848d02fac6cc70de5bd92',
    messagingSenderId: '384073856983',
    projectId: 'algonaid-4025a',
    storageBucket: 'algonaid-4025a.firebasestorage.app',
    androidClientId: '384073856983-caqhvjku2po103mpqo9g44m72b1pdo5r.apps.googleusercontent.com',
    iosClientId: '384073856983-fshcgklqtg7fk3kuu7tonnbbfq0k6281.apps.googleusercontent.com',
    iosBundleId: 'com.example.algonaidmobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQesXJs6UoJV0vnKuPwrrCXqjsiIa6xw',
    appId: '1:384073856983:ios:3848d02fac6cc70de5bd92',
    messagingSenderId: '384073856983',
    projectId: 'algonaid-4025a',
    storageBucket: 'algonaid-4025a.firebasestorage.app',
    androidClientId: '384073856983-caqhvjku2po103mpqo9g44m72b1pdo5r.apps.googleusercontent.com',
    iosClientId: '384073856983-fshcgklqtg7fk3kuu7tonnbbfq0k6281.apps.googleusercontent.com',
    iosBundleId: 'com.example.algonaidmobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6i2NNm5jQ7HfIDC6ro5byV3RDEme__wA',
    appId: '1:384073856983:web:7afdc7ea49e37ddfe5bd92',
    messagingSenderId: '384073856983',
    projectId: 'algonaid-4025a',
    authDomain: 'algonaid-4025a.firebaseapp.com',
    storageBucket: 'algonaid-4025a.firebasestorage.app',
    measurementId: 'G-34WNYZKDGZ',
  );

}